language: go
sudo: required

go:
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - tip
  - master

install:
  - sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install -y glide
  - go get -v github.com/mitchellh/gox
  - glide install

script:
  - go test -race -v .
  - gox -verbose