language: go
sudo: required

go:
  - 1.5.x
  - 1.6.x
  - 1.7.x
  - 1.8.x
  - tip
  - master

install:
  - sudo add-apt-repository -y ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install -y glide
  - go get -v github.com/mitchellh/gox
  - glide install

script:
  - go test -race -v .
  - gox -verbose -parallel=2

notifications:
  email:
    on_success: change
    on_failure: always

matrix:
  allow_failures:
    - go: master, tip